### ISSUE TITLE
cannot understand piservo.c

### ISSUE THREAD

**Issue by linchen1981** [wowczarek/ptpd#12]
Hi All,
I am working to bringup ptpd application with my hardware PTP feature, I am confused about the PI calculation in the source codes, 
there is calculation in the source file as blow,
    self->integral += (self->tau / self->delayFactor) * ((input + 0.0 ) * self->kI);
    self->output = (self->kP * (input + 0.0) ) + self->integral;

but what are kP and kI and what should be the value?

**Comment by wowczarek** [comment]
Hi - maybe you worked it out for yourself in the meantime, kP and kI are the proportional and integral gains of a PI controller (https://en.wikipedia.org/wiki/PID_controller). They are configurable in ptpd and have different defaults for hardware and software clocks. As to what the values should be... there are numerous books and PhD theses on this topic alone.
